### ISSUE TITLE
Class Loadouts available via GUI in administered Area

### ISSUE THREAD

**Issue by Ganvai** [Onill/German-Rangers#2]
Access to class loadout GUI only in a restricted area in the base (controlled by Admins / Zeus / Kilo).

**Comment by Ganvai** [comment]
Enhancement:

Players only see available loadouts:

Depending on your group and position, you only see the fitting loadouts.

If you are Sierra, you only see Sierra loadouts, if you are Echo, you only see Echo Loadouts

**Comment by Onill** [comment]
- [ ] Zug von ZugFü trennen

**Comment by Ganvai** [comment]
Längst getan:          
          Bug Meldung von Angel:

            Für jeden GUi Click im Menü wird ein neues GUI geöffnet, das alte aber nicht geschlossen. Klickt man sich durch 
            mehrere GUIs durch muss man danach auch die Anzahl wieder schließen. Das braucht nen Zusatz das wenn das neue 
           GUI geöffnet wird, das alte geschlossen wird.

Wunsch von Angel:
Sierra Loadouts verfügbar machen in Ansicht. Außerdem für Sierra Spieler nur Sierra Loadouts verfügbar machen.

**Comment by Onill** [comment]
Ich würde ungerne unnötige Ristrictionen einbauen.
