### ISSUE TITLE
Better Teleport Fnc

### ISSUE THREAD

**Issue by Onill** [Onill/German-Rangers#3]
Unterscheidung zwischen GruppenFü und anderen
Teleport in Fahrzeug
Abbruch-Hinweis

**Comment by Onill** [comment]
- [x] Unterscheidung zwischen GruppenFü und anderen
- [x] Teleport in Fahrzeug
- [x] Abbruch-Hinweis

- [x]  Localize

**Comment by Ganvai** [comment]
Alle Anforderungen umgesetzt
